export const product_card = [
  {
    id: 1,
    product_name: 'Rayes Alpha',
    description: 'Hands-free , Hands-on Music Experience',
    price: 350,
    currency: '$',
    thumb: './1.png',
    owner: 1,
  },
  {
    id: 2,
    product_name: 'Rayes Z30',
    description: 'Hands-free , Hands-on Music Experience',
    price: 250,
    currency: '$',
    thumb: './2.png',
    owner: 2,
  },
  {
    id: 3,
    product_name: 'Rayes X30',
    description: 'Hands-free , Hands-on Music Experience',
    price: 300,
    currency: '$',
    thumb: './3.png',
    owner: 3,
  },
  {
    id: 4,
    product_name: 'Rayes Alpha',
    description: 'Hands-free , Hands-on Music Experience',
    price: 350,
    currency: '$',
    thumb: './1.png',
    owner: 1,
  },
  {
    id: 5,
    product_name: 'Rayes Z30',
    description: 'Hands-free , Hands-on Music Experience',
    price: 250,
    currency: '$',
    thumb: './2.png',
    owner: 2,
  },
  {
    id: 6,
    product_name: 'Rayes X30',
    description: 'Hands-free , Hands-on Music Experience',
    price: 300,
    currency: '$',
    thumb: './3.png',
    owner: 3,
  },
  {
    id: 7,
    product_name: 'Rayes Alpha',
    description: 'Hands-free , Hands-on Music Experience',
    price: 350,
    currency: '$',
    thumb: './1.png',
    owner: 1,
  },
  {
    id: 8,
    product_name: 'Rayes Z30',
    description: 'Hands-free , Hands-on Music Experience',
    price: 250,
    currency: '$',
    thumb: './2.png',
    owner: 2,
  },
  {
    id: 9,
    product_name: 'Rayes X30',
    description: 'Hands-free , Hands-on Music Experience',
    price: 300,
    currency: '$',
    thumb: './3.png',
    owner: 3,
  },
];
export default product_card;
